#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEditor.Compilation;
using UnityEngine;

namespace Beneton.ECS.Core.CodeGen
{
	/// <summary>
	/// Automatically run the generator before each compilation.
	/// Comment out if you prefer manual control.
	/// </summary>
	[InitializeOnLoad]
	internal static class ComponentIdAutoGen
	{
		static ComponentIdAutoGen()
		{
			CompilationPipeline.compilationStarted -= OnCompilationStarted;
			CompilationPipeline.compilationStarted += OnCompilationStarted;
		}

		private static void OnCompilationStarted(object _)
		{
			// Run before the compiler actually processes the code.
			ComponentIdGenerator.Generate();
		}
	}

	/// <summary>
	/// Generates a single file containing partial structs for all IComponent implementations.
	/// </summary>
	internal static class ComponentIdGenerator
	{
		// Where to write the generated file
		private const string OutputFolder = "Assets/_Generated";
		private const string OutputFileName = "ComponentIds.g.cs";

		public static readonly string CoreNamespace = typeof(World).Namespace;
		
		// Explicit types of Components to search for
		public const string ComponentType = nameof(IComponent);
		public const string SingletonComponentType = nameof(ISingletonComponent);

		private const string IdProviderClass = nameof(ComponentTypeIdProvider);
		private const string IdProviderMethod = nameof(ComponentTypeIdProvider.Next);

		// Root folder to scan for components
		private const string ScanRoot = "Assets";

		public static void Generate()
		{
			try
			{
				if (!Directory.Exists(OutputFolder))
				{
					Directory.CreateDirectory(OutputFolder);
				}

				var components = ComponentSourceScanner.FindComponents(ScanRoot);

				var path = Path.Combine(OutputFolder, OutputFileName);
				var code = BuildFile(components);

				File.WriteAllText(path, code, Encoding.UTF8);
				AssetDatabase.Refresh();
			}
			catch (Exception ex)
			{
				Debug.LogError($"Component ID generation failed: {ex}");
			}
		}

		private static string BuildFile(
			IReadOnlyList<ComponentSourceScanner.ComponentDeclaration> components)
		{
			var sb = new StringBuilder();

			sb.AppendLine("// <auto-generated>");
			sb.AppendLine("// This file is generated. Do not edit manually.");
			sb.AppendLine("// </auto-generated>");
			sb.AppendLine();
			sb.AppendLine($"using {CoreNamespace};");
			sb.AppendLine();

			// Group by namespace so we can emit clean blocks
			var byNamespace = components
				.GroupBy(c => c.Namespace ?? string.Empty)
				.OrderBy(g => g.Key);

			foreach (var group in byNamespace)
			{
				var ns = group.Key;

				if (!string.IsNullOrEmpty(ns))
				{
					sb.Append("namespace ").Append(ns).AppendLine();
					sb.AppendLine("{");
				}

				foreach (var c in group.OrderBy(c => c.Name))
				{
					sb.AppendLine("    public partial struct " + c.Name);
					sb.AppendLine("    {");
					sb.AppendLine(
						"        public static int Id { get; } = " + IdProviderClass + "." +
						IdProviderMethod + "();");
					sb.AppendLine("        public int TypeId => Id;");
					sb.AppendLine("    }");
					sb.AppendLine();
				}

				if (!string.IsNullOrEmpty(ns))
				{
					sb.AppendLine("}");
					sb.AppendLine();
				}
			}

			return sb.ToString();
		}
	}


	/// <summary>
	/// Scans C# source files for structs a specific type.
	/// This works even if the project does not currently compile because we scan the text in the
	/// files. Using Reflection would not work here, unfortunately.
	/// </summary>
	internal static class ComponentSourceScanner
	{
		public sealed class ComponentDeclaration
		{
			public string Namespace;
			public string Name;
		}

		private static readonly Regex NamespaceRegex =
			new(@"\bnamespace\s+([A-Za-z0-9_.]+)", RegexOptions.Compiled);

		private static readonly Regex UsingRegex =
			new(@"using\s+([A-Za-z0-9_.]+)\s*;", RegexOptions.Compiled);

		private static readonly Regex StructRegex =
			new(
				@"\bstruct\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*(?<bases>[^{]+)",
				RegexOptions.Compiled);

		public static IReadOnlyList<ComponentDeclaration> FindComponents(string rootFolder)
		{
			var result = new List<ComponentDeclaration>();

			var files = Directory.GetFiles(rootFolder, "*.cs", SearchOption.AllDirectories);

			foreach (var file in files)
			{
				if (file.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase))
				{
					continue;
				}

				var text = File.ReadAllText(file);

				// Extract namespace
				var nsMatch = NamespaceRegex.Match(text);
				var ns = nsMatch.Success ? nsMatch.Groups[1].Value.Trim() : null;

				// Extract using directives
				var usings = UsingRegex.Matches(text)
					.Select(m => m.Groups[1].Value.Trim())
					.ToList();

				// Check structs
				var structMatches = StructRegex.Matches(text);
				foreach (Match m in structMatches)
				{
					var name = m.Groups[1].Value.Trim();
					var bases = m.Groups["bases"].Value.Trim();

					if (ImplementsTargetInterface(
							bases,
							usings,
							ComponentIdGenerator.ComponentType)
						||
						ImplementsTargetInterface(
							bases,
							usings,
							ComponentIdGenerator.SingletonComponentType))
					{
						result.Add(
							new ComponentDeclaration
							{
								Namespace = ns,
								Name = name
							});
					}
				}
			}

			return result;
		}

		private static bool ImplementsTargetInterface(
			string bases,
			List<string> usings,
			string componentType)
		{
			// Case 1: Fully-qualified
			if (bases.Contains(
				$"{ComponentIdGenerator.CoreNamespace}/{componentType}"))
			{
				return true;
			}

			// Case 2: Short name when correct using exists
			// Example "IComponent"
			if (bases.Contains(componentType))
			{
				if (usings.Contains(ComponentIdGenerator.CoreNamespace))
				{
					return true;
				}
			}

			// Case 3: Aliased namespace
			// Example: using Core = Beneton.ECS.Core;
			foreach (var u in usings)
			{
				if (u.Contains("="))
				{
					var parts = u.Split('=');
					var alias = parts[0].Trim();
					var full = parts[1].Trim();

					if (full == ComponentIdGenerator.CoreNamespace &&
						bases.Contains(alias + $".{componentType}"))
					{
						return true;
					}
				}
			}

			return false;
		}
	}
}
#endif