// <auto-generated>
// This file is generated. Do not edit manually.
// </auto-generated>

using Beneton.ECS.Core;

namespace ECSSample.Components
{
    public partial struct AddTravelerButton
    {
        public static int Id { get; } = ComponentTypeIdProvider.Next();
        public int TypeId => Id;
    }

    public partial struct Clicked
    {
        public static int Id { get; } = ComponentTypeIdProvider.Next();
        public int TypeId => Id;
    }

    public partial struct DirectionCommitment
    {
        public static int Id { get; } = ComponentTypeIdProvider.Next();
        public int TypeId => Id;
    }

    public partial struct ECSMeshRenderers
    {
        public static int Id { get; } = ComponentTypeIdProvider.Next();
        public int TypeId => Id;
    }

    public partial struct Movement
    {
        public static int Id { get; } = ComponentTypeIdProvider.Next();
        public int TypeId => Id;
    }

    public partial struct Resting
    {
        public static int Id { get; } = ComponentTypeIdProvider.Next();
        public int TypeId => Id;
    }

    public partial struct Traveler
    {
        public static int Id { get; } = ComponentTypeIdProvider.Next();
        public int TypeId => Id;
    }

    public partial struct TravelLog
    {
        public static int Id { get; } = ComponentTypeIdProvider.Next();
        public int TypeId => Id;
    }

}

