namespace Beneton.ECS.Core
{
	/// <summary>
	/// Represents the base interface for all ECS components.
	/// - All component data structures must implement this interface to be managed by the <see cref="ComponentManager"/>.
	/// - Implemented as <see langword="partial"/> <see langword="struct"/>s to support code generation and ensure cache-friendly data layout (optimal for <see cref="SparseSet{T}"/>).
	/// </summary>
	public interface IComponent
	{
		/// <summary>
		/// Gets the unique integer identifier for this component type.
		/// - Importance: This ID is essential for high-performance ECS operations, specifically for O(1) lookups in <see cref="SparseSet{T}"/> and fast matching in <see cref="Archetype"/>s.
		/// - Implementation: Usually assigned via a static ID generated by <see cref="ComponentTypeIdProvider"/> in auto-generated code.
		/// </summary>
		int TypeId { get; }
	}
}